### PR TITLE
Upgrade to jackson 2.5.4

### PR DESCRIPTION
**Pull request by codylerum**
Tried to keep this as small of change as possible.

This updates to 2.5.4 which is the current version of the 2.5.x which is what Amazon AWS is shipping.

This closes or supersedes #128 #130 #140 and #149

### CODE REVIEW

**Comment by carlosdp** [comment]
Awesome, thank you!

**Comment by okohll** [comment]
Thanks guys

**Comment by wgorder** [comment]
@carlosdp  how many years have to go by before we upgrade to jackson 2.  I hate having 2 versions on the classpath due to this transitive dep

**Comment by ptahchiev** [comment]
Well apparently it's not years, but decades. My app has more than 400 dependencies and the only one bringing old jackson is twilio. Most of the apps out there are spring and it's been ages since spring moved to the new jackson.

**Comment by codylerum** [comment]
I think we are going to see this in the next-gen branch.

 https://github.com/twilio/twilio-java/blob/next-gen/pom.xml#L37

No idea when this this will be ready for production.

**Comment by wgorder** [comment]
@codylerum well it looked like someone did the work and it was reverted.  This causes more and more issues the further it gets behind.  I suggest either not using a mainstream JSON library for this and do things the old fashion way, or else put more effort into keeping it up to date if you want your Twilio client to continue to be a viable option.

**Comment by carlosdp** [comment]
@wgorder it looks like the next-gen version is now released as version 7.x of the library and has an updated Jackson. This should be resolved.

**Comment by zugaldia** [comment]
@carlosdp Looking at all the 7.x versions published [on Maven](http://search.maven.org/#search%7Cga%7C1%7Ccom.twilio.sdk) they all ship with Jackson 2.4.3. Is there any other place we should be looking for a version of the Twilio Java SDK shipping Jackson 2.5.x or higher?

**Pull request merged**
