### PR TITLE
[blocked] feat!: Replace joda time with standard java.time

### LINKED ISSUE #409: Remove joda-time dependency
Can't you just use `java.time.LocalDateTime` instead? If you really need to use it, I suggest you mark the dependency as compile tome scope only and add some checks if the user has added joda-time in their classpath.

### PR DESCRIPTION
**Pull request by codylerum**
Fixes #409

While I know this cannot be merged to due Yoyodyne @childish-sambino suggested a PR may give the internal Twilio team something to look at.

Tests pass locally.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks for the PR @codylerum!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by codylerum** [comment]
This relates to #409

**Comment by childish-sambino** [comment]
Just an update: we're getting close to starting work on approving these changes and updating Yoyodyne. Stay tuned ...

**Comment by childish-sambino** [comment]
Closing in favor of https://github.com/twilio/twilio-java/pull/572 given the large number of generated files being changed and sync needed. We'll be releasing changes in the coming weeks.

**Pull request closed without merging**
