### PR TITLE
Added support for 'record' verb attribute to enable / disable recording both legs both legs of a call within the associated <Dial> verb

### PR DESCRIPTION
**Pull request by 4np**
See the [TwiML documentation](https://www.twilio.com/docs/api/twiml/dial) which describes the recording feature

### CODE REVIEW

**Comment by benkiefer** [comment]
Would love to see this get merged, but it looks like it might be a little out of date.

Can we get these updated to the string values that are supported for record (do-not-record, record-from-answer, record-from-ringing)?

**Comment by codylerum** [comment]
Should be able to support both the setRecord(boolean value) and setRecord(String value)

**Comment by benkiefer** [comment]
Thanks @codylerum, for some reason, I just missed it.

**Comment by codylerum** [comment]
@benkiefer No worries. I had to look 3 times for some reason :-)

**Comment by 4np** [comment]
:+1:

**Comment by skimbrel** [comment]
Looks good, thank you!

**Pull request merged**
