### PR TITLE
Drop json-simple and only use Jackson

### PR DESCRIPTION
**Pull request by codylerum**
Removes the json-simple dep and only uses Jackson

### CODE REVIEW

**Comment by carlosdp** [comment]
Thanks, I'll be reviewing this along with the preceding Jackson change after our deploy today.

**Comment by codylerum** [comment]
@carlosdp I'll go ahead and rebase this today. Anything else I should be on the lookout for?

**Comment by codylerum** [comment]
@carlosdp this now includes the reverted jackson upgrade

**Comment by codylerum** [comment]
Let me know when you are ready to rebase and try again.

**Comment by carlosdp** [comment]
@codylerum we recently completed a new version of the Java helper library which refactors everything nicely so there are no unnecessary dependencies. Since both changes require a major bump, I think we're just going to leave this version of the library alone in this respect to encourage people to upgrade to the new/better one.

The new library will have a release candidate out this month. Thanks!

**Comment by codylerum** [comment]
@carlosdp even better.

**Comment by tape88** [comment]
@carlosdp when update will be available ?

**Comment by carlosdp** [comment]
@tape88 we're releasing the release candidate mid next week

**Comment by jingming** [comment]
version `7.0.0` only uses Jackson.

**Pull request closed without merging**
